[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
force_single_line = true


[tool.mypy]
# mypy_path = 'src'
exclude = ["config"]
files  = '*.py'
warn_return_any = true
warn_unused_configs = true